name: Terraform Apply

on:
  workflow_dispatch:

jobs:
  terraform_plan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Azure login
        uses: azure/login@v2
        with:
          auth-type: IDENTITY
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Azure PowerShell script
        uses: azure/powershell@v1
        with:
          azPSVersion: "latest"
          inlineScript: |
            terraform init
            terraform plan -out=tfplan
        env:
          TF_VAR_discord_webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          TF_VAR_smtp_host: ${{ secrets.SMTP_HOST }}
          TF_VAR_smtp_port: ${{ secrets.SMTP_PORT }}
          TF_VAR_smtp_username: ${{ secrets.SMTP_USERNAME }}
          TF_VAR_smtp_password: ${{ secrets.SMTP_PASSWORD }}
          TF_VAR_smtp_from: ${{ secrets.SMTP_FROM }}

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v2
        with:
          name: tfplan
          path: tfplan

  terraform_apply:
    needs: terraform_plan
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Azure login
        uses: azure/login@v2
        with:
          auth-type: IDENTITY
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Azure PowerShell script
        uses: azure/powershell@v1
        with:
          azPSVersion: "latest"
          inlineScript: |
            terraform apply tfplan
        env:
          TF_VAR_discord_webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          TF_VAR_smtp_host: ${{ secrets.SMTP_HOST }}
          TF_VAR_smtp_port: ${{ secrets.SMTP_PORT }}
          TF_VAR_smtp_username: ${{ secrets.SMTP_USERNAME }}
          TF_VAR_smtp_password: ${{ secrets.SMTP_PASSWORD }}
          TF_VAR_smtp_from: ${{ secrets.SMTP_FROM }}